server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: root
  redis:
    host: 121.43.137.22
    port: 6379
    password: 0407bilibili
    database: 1
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  rabbitmq:
    host: 121.43.137.22 # IP地址
    port: 5672 # 端口号
    username: hmdianping # 用户名
    password: 123456 # 密码
    virtual-host: /hmdianping
    listener:
      simple:
        concurrency: 1
        max-concurrency: 1
        acknowledge-mode: manual
        prefetch: 1
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug

